apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: n8n-secret
type: Opaque
stringData:
  # IMPORTANT: Generate these values before deploying!
  # Generate encryption key: openssl rand -base64 32
  # Generate runner auth token: openssl rand -base64 24
  
  # Encryption Key (MUST be same across all n8n instances)
  N8N_ENCRYPTION_KEY: "PLACEHOLDER_REPLACED_BY_CI"
  
  # Queue Mode Configuration
  EXECUTIONS_MODE: "queue"
  QUEUE_BULL_REDIS_HOST: "redis-service.n8n.svc.cluster.local"
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  
  # Task Runners Configuration
  N8N_RUNNERS_ENABLED: "true"
  N8N_RUNNERS_MODE: "external"
  N8N_RUNNERS_AUTH_TOKEN: "PLACEHOLDER_REPLACED_BY_CI"
  N8N_RUNNERS_BROKER_LISTEN_ADDRESS: "0.0.0.0"
  N8N_RUNNERS_BROKER_PORT: "5679"
  N8N_RUNNERS_MAX_CONCURRENCY: "5"
  N8N_RUNNERS_TASK_TIMEOUT: "60"
  N8N_RUNNERS_HEARTBEAT_INTERVAL: "30"
  
  # Allow specific Node.js built-in modules in Code node
  # Examples: crypto,https,http,fs,path,url
  NODE_FUNCTION_ALLOW_BUILTIN: "crypto,https,http"
  
  # Allow external npm packages (from n8n's node_modules) in Code node
  # Examples: lodash,moment,axios
  # NODE_FUNCTION_ALLOW_EXTERNAL: "lodash"
  
  # Python standard library modules allowed in Code node
  # Examples: json,re,datetime,math,random
  N8N_RUNNERS_STDLIB_ALLOW: "json,re,datetime,math,random"
  
  # Optional: Webhook URL (set to your actual domain)
  # WEBHOOK_URL: "https://n8n.yourdomain.com"
  
  # Optional: Timezone
  GENERIC_TIMEZONE: "America/New_York"
  
  # Optional: Worker concurrency limit
  N8N_CONCURRENCY_PRODUCTION_LIMIT: "10"

