apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: n8n-main
  name: n8n-main
  namespace: n8n
spec:
  replicas: 1  # Main instance - can scale to multiple for HA with N8N_MULTI_MAIN_SETUP_ENABLED=true
  progressDeadlineSeconds: 900  # 15 minutes for initial startup
  selector:
    matchLabels:
      service: n8n-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: n8n-main
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: n8n-claim0
              mountPath: /data
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          ports:
            - containerPort: 5678
              name: http
            - containerPort: 5679
              name: task-broker
          env:
            # Database Configuration
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres-service.n8n.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            
            # n8n Basic Configuration
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
            
            # Queue Mode Configuration (from secret)
            - name: EXECUTIONS_MODE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: EXECUTIONS_MODE
            - name: QUEUE_BULL_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: QUEUE_BULL_REDIS_HOST
            - name: QUEUE_BULL_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: QUEUE_BULL_REDIS_PORT
            - name: QUEUE_HEALTH_CHECK_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: QUEUE_HEALTH_CHECK_ACTIVE
            
            # Encryption Key
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_ENCRYPTION_KEY
            
            # Task Runners Configuration
            - name: N8N_RUNNERS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_ENABLED
            - name: N8N_RUNNERS_MODE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_MODE
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_AUTH_TOKEN
            - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
            - name: N8N_RUNNERS_BROKER_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_BROKER_PORT
            
            # Code Node Permissions
            - name: NODE_FUNCTION_ALLOW_BUILTIN
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: NODE_FUNCTION_ALLOW_BUILTIN
            - name: N8N_RUNNERS_STDLIB_ALLOW
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_STDLIB_ALLOW
            
            # Optional: Timezone
            - name: GENERIC_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: GENERIC_TIMEZONE
                  optional: true
          
          resources:
            requests:
              memory: "640Mi"
              cpu: "200m"
            limits:
              memory: "1280Mi"
              cpu: "1000m"
          
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-claim0
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 5
      
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0

