apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5678
      targetPort: 5678
      protocol: TCP
    - name: task-broker
      port: 5679
      targetPort: 5679
      protocol: TCP
  selector:
    service: n8n-main
