apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: n8n
  POSTGRES_PASSWORD: PLACEHOLDER_REPLACED_BY_CI
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8n
  POSTGRES_NON_ROOT_PASSWORD: PLACEHOLDER_REPLACED_BY_CI