apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: redis-claim0
  name: redis-claim0
  namespace: n8n
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

